swagger: "2.0"
info:
  version: "1.0.0"
  title: "API de Película/Serie y Personaje"
paths:
  /movies:
    get:
      summary: Obtener lista de películas
      description: Devuelve una lista de todas las películas o filtra por nombre y orden
      security:
        - bearerAuth: []
      parameters:
        - name: name
          in: query
          description: Nombre de la película (opcional)
          required: false
          type: string
        - name: order
          in: query
          description: Orden de la lista ('asc' o 'desc') (opcional)
          required: false
          type: string
      responses:
        200:
          description: Operación exitosa
    post:
      summary: Crear una nueva película
      description: Crea una nueva película con los datos proporcionados
      security:
        - bearerAuth: []
      parameters:
        - name: body
          in: body
          description: Datos de la película a crear
          required: true
          schema:
            $ref: "#/definitions/PeliculaInput"
      responses:
        201:
          description: Película creada exitosamente
    delete:
      summary: Eliminar una película
      description: Elimina una película según su ID
      security:
        - bearerAuth: []
      parameters:
        - name: body
          in: body
          description: ID de la película a eliminar
          required: true
          schema:
            $ref: "#/definitions/PeliculaID"
      responses:
        200:
          description: Película eliminada exitosamente
    put:
      summary: Actualizar una película
      description: Actualiza una película existente con los datos proporcionados
      security:
        - bearerAuth: []
      parameters:
        - name: body
          in: body
          description: Datos de la película a actualizar
          required: true
          schema:
            $ref: "#/definitions/PeliculaUpdate"
      responses:
        200:
          description: Película actualizada exitosamente
  /characters:
    get:
      summary: Obtener lista de personajes
      description: Devuelve una lista de todos los personajes o filtra por nombre, edad y películas
      security:
        - bearerAuth: []
      parameters:
        - name: name
          in: query
          description: Nombre del personaje (opcional)
          required: false
          type: string
        - name: movie
          in: query
          description: ID de la película en la que aparece el personaje (opcional)
          required: false
          type: string
        - name: age
          in: query
          description: Edad del personaje (opcional)
          required: false
          type: integer
      responses:
        200:
          description: Operación exitosa
    post:
      summary: Crear un nuevo personaje
      description: Crea un nuevo personaje con los datos proporcionados
      security:
        - bearerAuth: []
      parameters:
        - name: body
          in: body
          description: Datos del personaje a crear
          required: true
          schema:
            $ref: "#/definitions/PersonajeInput"
      responses:
        201:
          description: Personaje creado exitosamente
    delete:
      summary: Eliminar un personaje
      description: Elimina un personaje según su ID
      security:
        - bearerAuth: []
      parameters:
        - name: body
          in: body
          description: ID del personaje a eliminar
          required: true
          schema:
            $ref: "#/definitions/PersonajeID"
      responses:
        200:
          description: Personaje eliminado exitosamente
    put:
      summary: Actualizar un personaje
      description: Actualiza un personaje existente con los datos proporcionados
      security:
        - bearerAuth: []
      parameters:
        - name: body
          in: body
          description: Datos del personaje a actualizar
          required: true
          schema:
            $ref: "#/definitions/PersonajeUpdate"
      responses:
        200:
          description: Personaje actualizado exitosamente

securityDefinitions:
  bearerAuth:
    type: apiKey
    name: Authorization
    in: header

definitions:
  PeliculaInput:
    type: object
    properties:
      imagen:
        type: string
  PeliculaID:
    type: object
    properties:
      id:
        type: string
  PeliculaUpdate:
    type: object
    properties:
      imagen:
        type: string
  PersonajeInput:
    type: object
    properties:
      nombre:
        type: string
  PersonajeID:
    type: object
    properties:
      id:
        type: string
  PersonajeUpdate:
    type: object
    properties:
      nombre:
        type: string
